# Generated by Django 5.0.4 on 2024-05-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidates_pics/'),
        ),
    ]
