# Generated by Django 5.0.4 on 2024-05-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
